### ISSUE TITLE
Message not found for errorCode: 0xC0000001

### ISSUE THREAD

**Issue by ravirajamiyer** [chenlichao-cn/wmi4j#1]
This is a good github project. I found this, when looking for a Java SDK to do WMI sessions on remote Windows server, from a client application using this library from a Linux machine. Even the sample program given is not working, and failing with the following message. Has this been tested in the scenario described above?

cn.chenlichao.wmi4j.WMIException: Message not found for errorCode: 0xC0000001
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:165)
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:177)
aused by: jcifs.smb.SmbException: Connection timeout
jcifs.util.transport.TransportException: Connection timeout
	at jcifs.util.transport.Transport.connect(Transport.java:178)
	at jcifs.smb.SmbTransport.connect(SmbTransport.java:290)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:139)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:847)
	at jcifs.smb.SmbFile.connect(SmbFile.java:890)

**Comment by zxy1403485490** [comment]
+1

**Comment by WeiMengDlink** [comment]
cn.chenlichao.wmi4j.WMIException: Message not found for errorCode: 0xC0000001
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:165)
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:177)
	at com.wlm.pro.service.SysMsgService.main(SysMsgService.java:48)
Caused by: jcifs.smb.SmbException
jcifs.util.transport.TransportException
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at jcifs.util.transport.Transport.readn(Transport.java:29)
	at jcifs.smb.SmbTransport.peekKey(SmbTransport.java:361)
	at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:271)
	at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:302)
	at jcifs.util.transport.Transport.run(Transport.java:240)
	at java.lang.Thread.run(Thread.java:745)

	at jcifs.util.transport.Transport.run(Transport.java:256)
	at java.lang.Thread.run(Thread.java:745)

	at jcifs.smb.SmbTransport.connect(SmbTransport.java:292)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:139)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:847)
	at jcifs.smb.SmbFile.connect(SmbFile.java:890)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:816)
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:73)
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:62)
	at jcifs.smb.SmbFile.getInputStream(SmbFile.java:2765)
	at rpc.ncacn_np.RpcTransport.attach(RpcTransport.java:90)
	at rpc.Stub.attach(Stub.java:105)
	at rpc.Stub.call(Stub.java:109)
	at org.jinterop.winreg.smb.JIWinRegStub.winreg_OpenHKLM(JIWinRegStub.java:100)
	at org.jinterop.dcom.core.JIProgId.getIdFromWinReg(JIProgId.java:122)
	at org.jinterop.dcom.core.JIProgId.getCorrespondingCLSID(JIProgId.java:154)
	at org.jinterop.dcom.core.JIComServer.<init>(JIComServer.java:395)
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:143)
	... 2 more

**Comment by fanxl12** [comment]
+1

**Comment by fanxl12** [comment]
cn.chenlichao.wmi4j.WMIException: Message not found for errorCode: 0xC0000001
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:165)
	at cn.chenlichao.wmi4j.SWbemLocator.connectServer(SWbemLocator.java:177)
	at com.fanxl.adddata.wmi.Wmi4jTest.main(Wmi4jTest.java:28)
Caused by: jcifs.smb.SmbException
jcifs.util.transport.TransportException
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at jcifs.util.transport.Transport.readn(Transport.java:29)
	at jcifs.smb.SmbTransport.peekKey(SmbTransport.java:361)
	at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:271)
	at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:302)
	at jcifs.util.transport.Transport.run(Transport.java:240)
	at java.lang.Thread.run(Thread.java:748)

	at jcifs.util.transport.Transport.run(Transport.java:256)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SuanCaiYv** [comment]
+1
